### ISSUE TITLE
Add a region field to the FireDepartment model.

### ISSUE THREAD

**Issue by garnertb** [garnertb/rogue_geonode#2]
- [x] Add a `region` field to the FireDepartment model, that has the name of the NFPA region that the department is within.
- [x] Include migration in commit.
- [x] Add a method to set the region on the FireDepartment model.

Regions:
![screen shot 2015-06-10 at 9 51 22 am](https://cloud.githubusercontent.com/assets/1141646/8083999/5d7ab8be-0f56-11e5-8365-1e938cbc0baa.png)

**Comment by meilinger** [comment]
_Assuming_ that DC is in the "South" region...should other areas (PR/MP/GU) be grouped under "South"?

**Comment by garnertb** [comment]
Yes, Northeast for DC.  Return None for PR, NO, GU for now.
On Jun 14, 2015 4:21 PM, "Joe Meilinger" notifications@github.com wrote:

_Assuming_ that DC is in the "Northeast" region should other states
(PR/MP/GU) be grouped under "South"?

**Comment by garnertb** [comment]
Sorry, looked at the map after that comment.  Yes, use "South" as the DC region not Northeast.

**Comment by meilinger** [comment]
Shoot...sorry, meant to submit this as a PR.  See https://github.com/garnertb/rogue_geonode/commit/c406c47739f08eafc95a8cf6875512d70f0483f8
