### ISSUE TITLE
Gracefully handle departments without stations

### ISSUE THREAD

**Issue by garnertb** [garnertb/rogue_geonode#26]
Currently the table is shown without any records.
<img width="576" alt="screen shot 2015-07-13 at 4 06 53 pm" src="https://cloud.githubusercontent.com/assets/1141646/8659476/3c623674-2979-11e5-95ae-2fc6feb672bc.png">

Instead, return a decent looking message that states something along the lines of "No stations have been linked to this department.".

**Comment by acengic** [comment]
URL or steps to recreate this issue?

**Comment by garnertb** [comment]
Here is one: /fire-departments/90354/theme

**Comment by acengic** [comment]
Thanks, this one shows the bug.
Is there a reason I do not see this fire department in “list view” 
http://192.168.99.100/fire-departments/theme/ ?

**Comment by garnertb** [comment]
We are currently filtering the list view to the priority departments which
are the base departments we want to have data for.  Once I get the search
working we'll show them all.

**Comment by acengic** [comment]
Tylor,
I’ve pushed changes for “partners” one html file and 20 or so images, this morning.
Issue 26 is completed so I was planning to send it to you for review, then I realized that  rogue_geonode folder is empty.
I’ve used TFS for a long time and haven’t used command line git for a long time. So I’m not sure what happened.

Can you check if you see my commit/push for partners?
Regards,
Arif

**Comment by garnertb** [comment]
I don't see any commits from you.
